language: r
dist: trusty

cache:
  directories:
    - $HOME/.cache/hdf5
    - $HOME/R/Library
addons:
  apt:
    packages:
    - libudunits2-dev                     # units > ggforce > ggraph > patchwork > dynplot
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_hdf5

install:
 - use_dynverse_devel
 - install_cran devtools covr
 - install_dynverse
 - install_withdeps
